# Generated by Django 6.0.2 on 2026-02-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip_code",
            field=models.CharField(default=12345, max_length=10),
            preserve_default=False,
        ),
    ]
