# Generated by Django 6.0.2 on 2026-02-12 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_address_zip_code"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table="store_customers",
        ),
    ]
