# Generated by Django 6.0.2 on 2026-02-14 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_auto_20260213_2125"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customer",
            new_name="store_custo_last_na_2e448d_idx",
            old_name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table="store_customer",
        ),
    ]
