# Generated by Django 6.0.2 on 2026-03-14 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_review_alter_collection_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$
DECLARE
    fk_name text;
BEGIN
    SELECT c.conname
    INTO fk_name
    FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    WHERE t.relname = 'store_cartitem'
      AND c.contype = 'f'
      AND pg_get_constraintdef(c.oid) LIKE 'FOREIGN KEY (cart_id)%REFERENCES store_cart(id)%';

    IF fk_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE "store_cartitem" DROP CONSTRAINT %I', fk_name);
    END IF;
END
$$;

ALTER TABLE "store_cart"
ALTER COLUMN "id" DROP IDENTITY IF EXISTS;

ALTER TABLE "store_cart"
ALTER COLUMN "id" TYPE uuid
USING lpad(to_hex("id"), 32, '0')::uuid;

ALTER TABLE "store_cart"
ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "store_cartitem"
ALTER COLUMN "cart_id" TYPE uuid
USING lpad(to_hex("cart_id"), 32, '0')::uuid;

ALTER TABLE "store_cartitem"
ADD CONSTRAINT "store_cartitem_cart_id_fk"
FOREIGN KEY ("cart_id") REFERENCES "store_cart" ("id")
DEFERRABLE INITIALLY DEFERRED;
""",
                    reverse_sql="""
ALTER TABLE "store_cartitem"
DROP CONSTRAINT IF EXISTS "store_cartitem_cart_id_fk";

ALTER TABLE "store_cartitem"
ALTER COLUMN "cart_id" TYPE bigint
USING ('x' || right(replace("cart_id"::text, '-', ''), 16))::bit(64)::bigint;

ALTER TABLE "store_cart"
ALTER COLUMN "id" TYPE bigint
USING ('x' || right(replace("id"::text, '-', ''), 16))::bit(64)::bigint;
""",
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="cart",
                    name="id",
                    field=models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                )
            ],
        ),
    ]
